In [1]:
import pandas as pd

from test_functions import *
from functions import *
from file_manager import *
from utils import *

In [2]:
process_excel_files(base_output_dir="mine", use_alternate="v1")

Creating output directory: mine\output_v3_26_07
Processing RDO No. 1 - Laoag City, Ilocos Norte.xls
Saved as: mine\output_v3_26_07\RDO_1_Sheet_9__DO_047_2023_.xlsx
Processing RDO No. 10 - Bontoc, Mt. Province.xls
Saved as: mine\output_v3_26_07\RDO_10_Sheet_3__DO_044_2022_.xlsx
Processing RDO No. 100 - Ozamiz City, Misamis Occidental.xls
Saved as: mine\output_v3_26_07\RDO_100_Sheet_5__DO_27_2020_.xlsx
Processing RDO No. 101 - Iligan City, Lanao del Norte.xls
Saved as: mine\output_v3_26_07\RDO_101_Sheet_6__DO_029_20_.xlsx
Processing RDO No. 102 - Marawi City, Lanao del Sur.xls
Saved as: mine\output_v3_26_07\RDO_102_Sheet_2__DO_37_20_.xlsx
Processing RDO No. 103 - Butuan City, Agusan del Norte.xls
Saved as: mine\output_v3_26_07\RDO_103_Sheet_9__064_2022_.xlsx
Processing RDO No. 104 - Bayugan City, Agusan del Sur.xls
Saved as: mine\output_v3_26_07\RDO_104_Sheet_5__DO_081_2022_.xlsx
Processing RDO No. 105 - Surigao City, Surigao del Norte.xls
Saved as: mine\output_v3_26_07\RDO_105_Sheet_5__DO_034_2023_.xlsx
Processing RDO No. 106 - Tandag City, Surigao del Sur.xls
Saved as: mine\output_v3_26_07\RDO_106_Sheet_5__DO_049_2022_.xlsx
Processing RDO No. 107 - Cotabato City, Maguindanao.xls
Saved as: mine\output_v3_26_07\RDO_107_Sheet_4__DO_053_2022_.xlsx
Processing RDO No. 108 - Kidapawan City, North Cotabato.xls
Saved as: mine\output_v3_26_07\RDO_108_Sheet_4__DO_009_2023_.xlsx
Processing RDO No. 109 - Tacurong City, Sultan Kudarat.xls
Saved as: mine\output_v3_26_07\RDO_109_Sheet_4__DO_07_2023_.xlsx
Processing RDO No. 11 -  Tabuk City, Kalinga.xls
Saved as: mine\output_v3_26_07\RDO_11_Sheet_4__DO_40_2020_.xlsx
Processing RDO No. 110 - General Santos City, South Cotabato.xls
Saved as: mine\output_v3_26_07\RDO_110_Sheet_9__DO_027_23.xlsx
Processing RDO No. 111 - Koronadal City, South Cotabato.xls
Saved as: mine\output_v3_26_07\RDO_111_Sheet_5__DO_075_2022_.xlsx
Processing RDO No. 112 - Tagum City, Davao del Norte.xlsx
Saved as: mine\output_v3_26_07\RDO_112_Sheet_5__DO_79_2019_.xlsx
Processing RDO NO. 113A - West Davao City.xlsx
Saved as: mine\output_v3_26_07\RDO_113A_Sheet_5__DO_032_21_.xlsx
Processing RDO No. 113B - East Davao City.xls
Saved as: mine\output_v3_26_07\RDO_113B_Sheet_5__033_2021_.xlsx
Processing RDO No. 114 - Mati City, Davao Oriental.xls
Saved as: mine\output_v3_26_07\RDO_114_Sheet_4__DO_029_2023_.xlsx
Processing RDO No. 115 - Digos City, Davao del Sur.XLS
Saved as: mine\output_v3_26_07\RDO_115_Sheet_4__DO_34_2021.xlsx
Processing RDO No. 12 - Lagawe, Ifugao.xlsx
Saved as: mine\output_v3_26_07\RDO_12_Sheet4__DO_74_18.xlsx
Processing RDO No. 13 - Tuguegarao City, Cagayan.xls
Saved as: mine\output_v3_26_07\RDO_13_Sheet_8__DO_028_2024_.xlsx
Processing RDO No. 14 - Bayombong, Nueva Vizcaya.xls
Saved as: mine\output_v3_26_07\RDO_14_Sheet_4__029_22_.xlsx
Processing RDO No. 15 - Naguilian, Isabela.xls
Saved as: mine\output_v3_26_07\RDO_15_Sheet_3__DO_23_2023_.xlsx
Processing RDO No. 16 - Cabarroguis, Quirino.xls
Saved as: mine\output_v3_26_07\RDO_16_Sheet_4__DO_30_22_.xlsx
Processing RDO No. 17A - Tarlac City, Tarlac.xls
Saved as: mine\output_v3_26_07\RDO_17A_Sheet_4__DO_15_2020_.xlsx
Processing RDO No. 17B - Paniqui Tarlac.xls
Saved as: mine\output_v3_26_07\RDO_17B_Sheet_4__DO_40_21_.xlsx
Processing RDO No. 18 - Olongapo City, Zambales.xls
Saved as: mine\output_v3_26_07\RDO_18_Sheet_4__DO_19_22_.xlsx
Processing RDO No. 2 - Vigan City, Ilocos Sur.xls
Saved as: mine\output_v3_26_07\RDO_2_Sheet_5__DO_28_23_.xlsx
Processing RDO No. 20 - Balanga City, Bataan.xls
Saved as: mine\output_v3_26_07\RDO_20_Sheet_4__DO_22_2022_.xlsx
Processing RDO No. 21A - Angeles City, North Pampanga.xls
Saved as: mine\output_v3_26_07\RDO_21A_Sheet_6__DO_056_22_.xlsx
Processing RDO No. 21B - City of San Fernando, South Pampanga.xls
Saved as: mine\output_v3_26_07\RDO_21B_Sheet_9__DO_004_2024_.xlsx
Processing RDO No. 22 - Baler Aurora.xls
Saved as: mine\output_v3_26_07\RDO_22_Sheet_4__DO_69_2023_.xlsx
Processing RDO No. 23A - Talavera, North Nueva Ecija.xls
Saved as: mine\output_v3_26_07\RDO_23A_Sheet_4__DO_50_2023_.xlsx
Processing RDO No. 23B - Cabanatuan City, South Nueva Ecija.xls
Saved as: mine\output_v3_26_07\RDO_23B_Sheet_5__DO_39_22_.xlsx
Processing RDO No. 24 - Valenzuela City.xls
Saved as: mine\output_v3_26_07\RDO_24_Sheet_6__DO_009_2021_.xlsx
Processing RDO No. 25A - Plaridel, Bulacan.xlsx
Saved as: mine\output_v3_26_07\RDO_25A_Sheet_9__DO_009_2020_.xlsx
Processing RDO No. 25B - Sta. Maria, Bulacan.xlsx
Saved as: mine\output_v3_26_07\RDO_25B_Sheet_9__DO_14_18_.xlsx
Processing RDO No. 26 - Malabon-Navotas.xls
Saved as: mine\output_v3_26_07\RDO_26_Sheet_8__DO_046_2022_.xlsx
Processing RDO No. 27 - Caloocan City.xls
Saved as: mine\output_v3_26_07\RDO_27_Sheet_8__DO_046_2023_.xlsx
Processing RDO No. 28 - Novaliches, Quezon City.xls
Saved as: mine\output_v3_26_07\RDO_28_Sheet_8__DO_037_2024_.xlsx
Processing RDO No. 29 - Tondo-San Nicolas.xls
Saved as: mine\output_v3_26_07\RDO_29_Sheet_7__DO_27_19_.xlsx
Processing RDO No. 3 - San Fernando City, La Union.xls
Saved as: mine\output_v3_26_07\RDO_3_Sheet_8__DO_045_19__.xlsx
Processing RDO No. 30 - Binondo.xls
Saved as: mine\output_v3_26_07\RDO_30_Sheet_6__DO_62_17_.xlsx
Processing RDO No. 31 - Sta. Cruz, Manila.xls
Saved as: mine\output_v3_26_07\RDO_31_Sheet_6__DO_077_18_.xlsx
Processing RDO No. 32 - Quiapo-Sampaloc-San Miguel-Sta Mesa.xls
Saved as: mine\output_v3_26_07\RDO_32_Sheet_6__DO_21_19_.xlsx
Processing RDO No. 33 - Intramuros-Ermita-Malate.xls
Saved as: mine\output_v3_26_07\RDO_33_Sheet_6__DO_75_17_.xlsx
Processing RDO No. 34 - Paco-Pandacan-Sta. Ana-San Andres.xls
Saved as: mine\output_v3_26_07\RDO_34_Sheet_6__DO_78_19_.xlsx
Processing RDO No. 35 - Odiongan, Romblon.xls
Saved as: mine\output_v3_26_07\RDO_35_Sheet_3__DO_026_2021_.xlsx
Processing RDO No. 36 - Puerto Princesa City, Palawan.xls
Saved as: mine\output_v3_26_07\RDO_36_Sheet_3__DO_72_17.xlsx
Processing RDO No. 37 - SanJose, Occidental Mindoro.xls
Saved as: mine\output_v3_26_07\RDO_37_Sheet_4__DO_045_2022_.xlsx
Processing RDO No. 38 - North Quezon City.xls
Saved as: mine\output_v3_26_07\RDO_38_Sheet_8__DO_033_2024_.xlsx
Processing RDO No. 39 - South Quezon City.xls
Saved as: mine\output_v3_26_07\RDO_39_Sheet_8__DO_007_2024_.xlsx
Processing RDO No. 4 - Calasiao, Central Pangasinan.xls
Saved as: mine\output_v3_26_07\RDO_4_Sheet_12__DO015_2023_.xlsx
Processing RDO No. 40 - Cubao.xls
Saved as: mine\output_v3_26_07\RDO_40_Sheet_8__DO_035_2024_.xlsx
Processing RDO No. 41 - Mandaluyong City.xls
Saved as: mine\output_v3_26_07\RDO_41_Sheet_9__DO_059_2022.xlsx
Processing RDO No. 42 - San Juan City.xls
Saved as: mine\output_v3_26_07\RDO_42_Sheet_8__DO_022_2023_.xlsx
Processing RDO No. 43 - Pasig City.xls
Saved as: mine\output_v3_26_07\RDO_43_Sheet_9__DO_24_2023_.xlsx
Processing RDO No. 44 - Taguig-Pateros.xlsx
Saved as: mine\output_v3_26_07\RDO_44_Sheet_9__DO_005_24_.xlsx
Processing RDO No. 45 - Marikina City.xls
Saved as: mine\output_v3_26_07\RDO_45_Sheet_11__DO_06_2023_.xlsx
Processing RDO No. 46 - Cainta-Taytay.xls
Saved as: mine\output_v3_26_07\RDO_46_Sheet_7__DO_22_2020_.xlsx
Processing RDO No. 47 - East Makati.xls
Saved as: mine\output_v3_26_07\RDO_47_Sheet_8__DO_37_2021_.xlsx
Processing RDO No. 48 - West Makati.xls
Saved as: mine\output_v3_26_07\RDO_48_Sheet_9__DO_36_2021_.xlsx
Processing RDO No. 49 - North Makati City.xls
Saved as: mine\output_v3_26_07\RDO_49_Sheet_7__DO_35_2021_.xlsx
Processing RDO No. 5 - Alaminos City, West Pangasinan.xls
Saved as: mine\output_v3_26_07\RDO_5_Sheet_11__DO_082_2022_.xlsx
Processing RDO No. 50 - South Makati.xls
Saved as: mine\output_v3_26_07\RDO_50_Sheet_9__DO_38_2021_.xlsx
Processing RDO No. 51 - Pasay City.xls
Saved as: mine\output_v3_26_07\RDO_51_Sheet_7__DO_43_2023_.xlsx
Processing RDO No. 52 - Paranaque City.xls
Saved as: mine\output_v3_26_07\RDO_52_Sheet_10__DO_049_23_.xlsx
Processing RDO No. 53A - Las Pinas City.xls
Saved as: mine\output_v3_26_07\RDO_53A_Sheet_9__DO_004_2021_.xlsx
Processing RDO No. 53B - Muntinlupa City.xls
Saved as: mine\output_v3_26_07\RDO_53B_Sheet_10__DO_089_2023_.xlsx
Processing RDO No. 54A - Trece Martirez City, East Cavite.xls
Saved as: mine\output_v3_26_07\RDO_54A_Sheet_11__DO_20_21_.xlsx
Processing RDO No. 54B - Bacoor City, West Cavite.xls
Saved as: mine\output_v3_26_07\RDO_54B_Sheet_8__DO_33_22_.xlsx
Processing RDO No. 55 - San Pablo City, East Laguna.xls
Saved as: mine\output_v3_26_07\RDO_55_Sheet_9__DO_018_20.xlsx
Processing RDO No. 56 - Calamba City, Central Laguna.xls
Saved as: mine\output_v3_26_07\RDO_56_Sheet_17__DO_059_23_.xlsx
Processing RDO No. 57 - Biñan City, West Laguna.xls
Saved as: mine\output_v3_26_07\RDO_57_Sheet_10__DO_055_24.xlsx
Processing RDO No. 58 - Batangas City, West Batangas.xlsx

C:\Users\oyutn\PycharmProjects\bir-zl-scraping\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

Saved as: mine\output_v3_26_07\RDO_58_Sheet_7__DO_35_2022_.xlsx
Processing RDO No. 59 - Lipa City, East Batangas.xls
Saved as: mine\output_v3_26_07\RDO_59_Sheet_8__34_22_.xlsx
Processing RDO No. 6 - Urdaneta City, East Pangasinan.xls
Saved as: mine\output_v3_26_07\RDO_6_Sheet_11__48_22_.xlsx
Processing RDO No. 60 - Lucena City, North Quezon.xls
Saved as: mine\output_v3_26_07\RDO_60_Sheet_7__DO_13_2020_.xlsx
Processing RDO No. 61 - Gumaca, South Quezon.xls
Saved as: mine\output_v3_26_07\RDO_61_Sheet_9__DO_037_2022_.xlsx
Processing RDO No. 62 - Boac, Marinduque.xls
Saved as: mine\output_v3_26_07\RDO_62_Sheet_4__DO_40_22_.xlsx
Processing RDO No. 63 - Calapan City,  Oriental Mindoro.XLS
Saved as: mine\output_v3_26_07\RDO_63_Sheet_6__DO_43_22_.xlsx
Processing RDO No. 64 - Talisay, Camarines Norte.xls
Saved as: mine\output_v3_26_07\RDO_64_Sheet_7__DO_015_2024_.xlsx
Processing RDO No. 65 - Naga City, Camarines Sur.xls
Saved as: mine\output_v3_26_07\RDO_65_Sheet_8__DO_034_2024_.xlsx
Processing RDO No. 66 - Iriga City, Camarines Sur.xls
Saved as: mine\output_v3_26_07\RDO_66_Sheet_4__DO_009_2024_.xlsx
Processing RDO No. 67 - Legazpi City, Albay.xls
Saved as: mine\output_v3_26_07\RDO_67_Sheet_7__DO_016_2024_.xlsx
Processing RDO No. 68 - Sorsogon City, Sorsogon.xls
Saved as: mine\output_v3_26_07\RDO_68_Sheet_4__DO_002_2024_.xlsx
Processing RDO No. 69 - Virac, Catanduanes.xls
Saved as: mine\output_v3_26_07\RDO_69_Sheet_4__DO_006_2024_.xlsx
Processing RDO No. 7 - Bangued, Abra.xls
Saved as: mine\output_v3_26_07\RDO_7_Sheet_4__DO_016_21_.xlsx
Processing RDO No. 70 - Masbate City, Masbate.xls
Saved as: mine\output_v3_26_07\RDO_70_Sheet_4__DO_010_2024_.xlsx
Processing RDO No. 71 - Kalibo, Aklan.xls
Saved as: mine\output_v3_26_07\RDO_71_Sheet_6__DO_010_2021_.xlsx
Processing RDO No. 72 - Roxas City, Capiz.xls
Saved as: mine\output_v3_26_07\RDO_72_Sheet_6__DO_025_2021_.xlsx
Processing RDO No. 73 - San Jose, Antique.xls
Saved as: mine\output_v3_26_07\RDO_73_Sheet_4__DO_14_2021_.xlsx
Processing RDO No. 74 - Iloilo City, Iloilo.xls
Saved as: mine\output_v3_26_07\RDO_74_Sheet_9__DO17_2021_.xlsx
Processing RDO No. 75 - Zarraga, Iloilo.xls
Saved as: mine\output_v3_26_07\RDO_75_Sheet_4__DO_13_2021_.xlsx
Processing RDO No. 76 - Victorias City, Negros Occidental.xls
Saved as: mine\output_v3_26_07\RDO_76_Sheet_4__DO_75_2023_.xlsx
Processing RDO No. 77 - Bacolod City Negros Occidental.xls
Saved as: mine\output_v3_26_07\RDO_77_Sheet_7__DO_058_2023_.xlsx
Processing RDO No. 78 - Binalbagan, Negros Occidental.xls
Saved as: mine\output_v3_26_07\RDO_78_Sheet_10__077_23_.xlsx
Processing RDO No. 79 - Dumaguete City, Negros Oriental.xls
Saved as: mine\output_v3_26_07\RDO_79_Sheet_3__DO_078_2018_.xlsx
Processing RDO No. 8 - Baguio City.xls
Saved as: mine\output_v3_26_07\RDO_8_Sheet_5__DO_074_23_.xlsx
Processing RDO No. 80 - Mandaue City, Cebu.xls
Saved as: mine\output_v3_26_07\RDO_80__Sheet_11__DO_23_2022_.xlsx
Processing RDO No. 81 - Cebu City North.xlsx
Saved as: mine\output_v3_26_07\RDO_81_Sheet_6__DO_054_2023_.xlsx
Processing RDO No. 82 - Cebu City, South.xls
Saved as: mine\output_v3_26_07\RDO_82_Sheet_6__DO_86_2023_.xlsx
Processing RDO No. 83 - Talisay City, CebuWeb.xls
Saved as: mine\output_v3_26_07\RDO_83_Sheet_8_060_22_.xlsx
Processing RDO No. 84 - Tagbilaran City, Bohol.XLS
Saved as: mine\output_v3_26_07\RDO_84_Sheet_6__DO_043_2024_.xlsx
Processing RDO No. 85 - Catarman, Northern Samar.xls
Saved as: mine\output_v3_26_07\RDO_85_Sheet_4__DO_053_24_.xlsx
Processing RDO No. 86 - Borongan City, Eastern Samar.xls
Saved as: mine\output_v3_26_07\RDO_86_Sheet_4__DO_07_2019_.xlsx
Processing RDO No. 87 - Catbalogan City.xls
Saved as: mine\output_v3_26_07\RDO_87_Sheet_3__D0_19_2010_.xlsx
Processing RDO No. 88 - Tacloban City, Leyte.xls
Saved as: mine\output_v3_26_07\RDO_88_Sheet_10__DO_011_24_.xlsx
Processing RDO No. 89 - Ormoc City, Leyte.xls
Saved as: mine\output_v3_26_07\RDO_89_Sheet_7__DO_042_2024_.xlsx
Processing RDO No. 9 - La Trinidad, Benguet.xlsx
Saved as: mine\output_v3_26_07\RDO_9_Sheet_3__DO_12_2018_.xlsx
Processing RDO No. 90 - Maasin City, Southern Leyte.xls
Saved as: mine\output_v3_26_07\RDO_90_Sheet_5__DO_NO__055_2023_.xlsx
Processing RDO No. 91 - Dipolog City, Zamboanga del Norte.xls
Saved as: mine\output_v3_26_07\RDO_91_Sheet_6__DO_073_2018_.xlsx
Processing RDO No. 92 - Pagadian City, Zamboanga del Sur.xls
Saved as: mine\output_v3_26_07\RDO_92_Sheet_4__DO_014_2023_.xlsx
Processing RDO No. 93A - Zamboanga City, Zamboanga Del Sur.xlsx
Saved as: mine\output_v3_26_07\RDO_93A_Sheet_5__DO_008_2024_.xlsx
Processing RDO No. 93B - Ipil, Zamboanga Sibugay (WEBSITE REUPLOADING).xls
Saved as: mine\output_v3_26_07\RDO_93B_Sheet_4__DO_58_2019_.xlsx
Processing RDO No. 94 - Isabela City,  Basilan.xls
Saved as: mine\output_v3_26_07\RDO_94_Sheet_2__DO_031_2023_.xlsx
Processing RDO No. 95 - Jolo, Sulu.xls
Saved as: mine\output_v3_26_07\RDO_95_Sheet_2__DO_003_2021_.xlsx
Processing RDO No. 96 - Bongao, Tawi-Tawi.xls
Saved as: mine\output_v3_26_07\RDO_96_Sheet_5__DO_45_23_.xlsx
Processing RDO No. 97 - Gingoog City, Misamis Oriental.xls
Saved as: mine\output_v3_26_07\RDO_97_Sheet_7__DO_012_2023_.xlsx
Processing RDO No. 98 - Cagayan de Oro City, Misamis Oriental.xls
Saved as: mine\output_v3_26_07\RDO_98_Sheet_9__DO_032_2023_.xlsx
Processing RDO No. 99 - Malaybalay City, Bukidnon.xlsx
Saved as: mine\output_v3_26_07\RDO_99_Sheet_4__DO_047___22_.xlsx
No annotations were generated.

Processing complete: 122 files processed, 0 files skipped.
Output directory: mine\output_v3_26_07

'mine\\output_v3_26_07'

In [4]:
process_excel_files(base_output_dir="google", use_alternate="v2")

Creating output directory: google\output_v1_26_07
Processing RDO No. 1 - Laoag City, Ilocos Norte.xls
Saved as: google\output_v1_26_07\RDO_1_Sheet_9__DO_047_2023_.xlsx
Processing RDO No. 10 - Bontoc, Mt. Province.xls
Saved as: google\output_v1_26_07\RDO_10_Sheet_3__DO_044_2022_.xlsx
Processing RDO No. 100 - Ozamiz City, Misamis Occidental.xls
Saved as: google\output_v1_26_07\RDO_100_Sheet_5__DO_27_2020_.xlsx
Processing RDO No. 101 - Iligan City, Lanao del Norte.xls
Saved as: google\output_v1_26_07\RDO_101_Sheet_6__DO_029_20_.xlsx
Processing RDO No. 102 - Marawi City, Lanao del Sur.xls
Saved as: google\output_v1_26_07\RDO_102_Sheet_2__DO_37_20_.xlsx
Processing RDO No. 103 - Butuan City, Agusan del Norte.xls
Saved as: google\output_v1_26_07\RDO_103_Sheet_9__064_2022_.xlsx
Processing RDO No. 104 - Bayugan City, Agusan del Sur.xls
Saved as: google\output_v1_26_07\RDO_104_Sheet_5__DO_081_2022_.xlsx
Processing RDO No. 105 - Surigao City, Surigao del Norte.xls
Saved as: google\output_v1_26_07\RDO_105_Sheet_5__DO_034_2023_.xlsx
Processing RDO No. 106 - Tandag City, Surigao del Sur.xls
Saved as: google\output_v1_26_07\RDO_106_Sheet_5__DO_049_2022_.xlsx
Processing RDO No. 107 - Cotabato City, Maguindanao.xls
Saved as: google\output_v1_26_07\RDO_107_Sheet_4__DO_053_2022_.xlsx
Processing RDO No. 108 - Kidapawan City, North Cotabato.xls
Saved as: google\output_v1_26_07\RDO_108_Sheet_4__DO_009_2023_.xlsx
Processing RDO No. 109 - Tacurong City, Sultan Kudarat.xls
Saved as: google\output_v1_26_07\RDO_109_Sheet_4__DO_07_2023_.xlsx
Processing RDO No. 11 -  Tabuk City, Kalinga.xls
Saved as: google\output_v1_26_07\RDO_11_Sheet_4__DO_40_2020_.xlsx
Processing RDO No. 110 - General Santos City, South Cotabato.xls
Saved as: google\output_v1_26_07\RDO_110_Sheet_9__DO_027_23.xlsx
Processing RDO No. 111 - Koronadal City, South Cotabato.xls
Saved as: google\output_v1_26_07\RDO_111_Sheet_5__DO_075_2022_.xlsx
Processing RDO No. 112 - Tagum City, Davao del Norte.xlsx
Saved as: google\output_v1_26_07\RDO_112_Sheet_5__DO_79_2019_.xlsx
Processing RDO NO. 113A - West Davao City.xlsx
Saved as: google\output_v1_26_07\RDO_113A_Sheet_5__DO_032_21_.xlsx
Processing RDO No. 113B - East Davao City.xls
Saved as: google\output_v1_26_07\RDO_113B_Sheet_5__033_2021_.xlsx
Processing RDO No. 114 - Mati City, Davao Oriental.xls
Saved as: google\output_v1_26_07\RDO_114_Sheet_4__DO_029_2023_.xlsx
Processing RDO No. 115 - Digos City, Davao del Sur.XLS
Saved as: google\output_v1_26_07\RDO_115_Sheet_4__DO_34_2021.xlsx
Processing RDO No. 12 - Lagawe, Ifugao.xlsx
Saved as: google\output_v1_26_07\RDO_12_Sheet4__DO_74_18.xlsx
Processing RDO No. 13 - Tuguegarao City, Cagayan.xls
Saved as: google\output_v1_26_07\RDO_13_Sheet_8__DO_028_2024_.xlsx
Processing RDO No. 14 - Bayombong, Nueva Vizcaya.xls
Saved as: google\output_v1_26_07\RDO_14_Sheet_4__029_22_.xlsx
Processing RDO No. 15 - Naguilian, Isabela.xls
Saved as: google\output_v1_26_07\RDO_15_Sheet_3__DO_23_2023_.xlsx
Processing RDO No. 16 - Cabarroguis, Quirino.xls
Saved as: google\output_v1_26_07\RDO_16_Sheet_4__DO_30_22_.xlsx
Processing RDO No. 17A - Tarlac City, Tarlac.xls
Saved as: google\output_v1_26_07\RDO_17A_Sheet_4__DO_15_2020_.xlsx
Processing RDO No. 17B - Paniqui Tarlac.xls
Saved as: google\output_v1_26_07\RDO_17B_Sheet_4__DO_40_21_.xlsx
Processing RDO No. 18 - Olongapo City, Zambales.xls
Saved as: google\output_v1_26_07\RDO_18_Sheet_4__DO_19_22_.xlsx
Processing RDO No. 2 - Vigan City, Ilocos Sur.xls
Saved as: google\output_v1_26_07\RDO_2_Sheet_5__DO_28_23_.xlsx
Processing RDO No. 20 - Balanga City, Bataan.xls
Saved as: google\output_v1_26_07\RDO_20_Sheet_4__DO_22_2022_.xlsx
Processing RDO No. 21A - Angeles City, North Pampanga.xls
Saved as: google\output_v1_26_07\RDO_21A_Sheet_6__DO_056_22_.xlsx
Processing RDO No. 21B - City of San Fernando, South Pampanga.xls
Saved as: google\output_v1_26_07\RDO_21B_Sheet_9__DO_004_2024_.xlsx
Processing RDO No. 22 - Baler Aurora.xls
Saved as: google\output_v1_26_07\RDO_22_Sheet_4__DO_69_2023_.xlsx
Processing RDO No. 23A - Talavera, North Nueva Ecija.xls
Saved as: google\output_v1_26_07\RDO_23A_Sheet_4__DO_50_2023_.xlsx
Processing RDO No. 23B - Cabanatuan City, South Nueva Ecija.xls
Saved as: google\output_v1_26_07\RDO_23B_Sheet_5__DO_39_22_.xlsx
Processing RDO No. 24 - Valenzuela City.xls
Saved as: google\output_v1_26_07\RDO_24_Sheet_6__DO_009_2021_.xlsx
Processing RDO No. 25A - Plaridel, Bulacan.xlsx
Saved as: google\output_v1_26_07\RDO_25A_Sheet_9__DO_009_2020_.xlsx
Processing RDO No. 25B - Sta. Maria, Bulacan.xlsx
Saved as: google\output_v1_26_07\RDO_25B_Sheet_9__DO_14_18_.xlsx
Processing RDO No. 26 - Malabon-Navotas.xls
Saved as: google\output_v1_26_07\RDO_26_Sheet_8__DO_046_2022_.xlsx
Processing RDO No. 27 - Caloocan City.xls
Saved as: google\output_v1_26_07\RDO_27_Sheet_8__DO_046_2023_.xlsx
Processing RDO No. 28 - Novaliches, Quezon City.xls
Saved as: google\output_v1_26_07\RDO_28_Sheet_8__DO_037_2024_.xlsx
Processing RDO No. 29 - Tondo-San Nicolas.xls
Saved as: google\output_v1_26_07\RDO_29_Sheet_7__DO_27_19_.xlsx
Processing RDO No. 3 - San Fernando City, La Union.xls
Saved as: google\output_v1_26_07\RDO_3_Sheet_8__DO_045_19__.xlsx
Processing RDO No. 30 - Binondo.xls
Saved as: google\output_v1_26_07\RDO_30_Sheet_6__DO_62_17_.xlsx
Processing RDO No. 31 - Sta. Cruz, Manila.xls
Saved as: google\output_v1_26_07\RDO_31_Sheet_6__DO_077_18_.xlsx
Processing RDO No. 32 - Quiapo-Sampaloc-San Miguel-Sta Mesa.xls
Saved as: google\output_v1_26_07\RDO_32_Sheet_6__DO_21_19_.xlsx
Processing RDO No. 33 - Intramuros-Ermita-Malate.xls
Saved as: google\output_v1_26_07\RDO_33_Sheet_6__DO_75_17_.xlsx
Processing RDO No. 34 - Paco-Pandacan-Sta. Ana-San Andres.xls
Saved as: google\output_v1_26_07\RDO_34_Sheet_6__DO_78_19_.xlsx
Processing RDO No. 35 - Odiongan, Romblon.xls
Saved as: google\output_v1_26_07\RDO_35_Sheet_3__DO_026_2021_.xlsx
Processing RDO No. 36 - Puerto Princesa City, Palawan.xls
Saved as: google\output_v1_26_07\RDO_36_Sheet_3__DO_72_17.xlsx
Processing RDO No. 37 - SanJose, Occidental Mindoro.xls
Saved as: google\output_v1_26_07\RDO_37_Sheet_4__DO_045_2022_.xlsx
Processing RDO No. 38 - North Quezon City.xls
Saved as: google\output_v1_26_07\RDO_38_Sheet_8__DO_033_2024_.xlsx
Processing RDO No. 39 - South Quezon City.xls
Saved as: google\output_v1_26_07\RDO_39_Sheet_8__DO_007_2024_.xlsx
Processing RDO No. 4 - Calasiao, Central Pangasinan.xls
Saved as: google\output_v1_26_07\RDO_4_Sheet_12__DO015_2023_.xlsx
Processing RDO No. 40 - Cubao.xls
Saved as: google\output_v1_26_07\RDO_40_Sheet_8__DO_035_2024_.xlsx
Processing RDO No. 41 - Mandaluyong City.xls
Saved as: google\output_v1_26_07\RDO_41_Sheet_9__DO_059_2022.xlsx
Processing RDO No. 42 - San Juan City.xls
Saved as: google\output_v1_26_07\RDO_42_Sheet_8__DO_022_2023_.xlsx
Processing RDO No. 43 - Pasig City.xls
Saved as: google\output_v1_26_07\RDO_43_Sheet_9__DO_24_2023_.xlsx
Processing RDO No. 44 - Taguig-Pateros.xlsx
Saved as: google\output_v1_26_07\RDO_44_Sheet_9__DO_005_24_.xlsx
Processing RDO No. 45 - Marikina City.xls
Saved as: google\output_v1_26_07\RDO_45_Sheet_11__DO_06_2023_.xlsx
Processing RDO No. 46 - Cainta-Taytay.xls
Saved as: google\output_v1_26_07\RDO_46_Sheet_7__DO_22_2020_.xlsx
Processing RDO No. 47 - East Makati.xls
Saved as: google\output_v1_26_07\RDO_47_Sheet_8__DO_37_2021_.xlsx
Processing RDO No. 48 - West Makati.xls
Saved as: google\output_v1_26_07\RDO_48_Sheet_9__DO_36_2021_.xlsx
Processing RDO No. 49 - North Makati City.xls
Saved as: google\output_v1_26_07\RDO_49_Sheet_7__DO_35_2021_.xlsx
Processing RDO No. 5 - Alaminos City, West Pangasinan.xls
Saved as: google\output_v1_26_07\RDO_5_Sheet_11__DO_082_2022_.xlsx
Processing RDO No. 50 - South Makati.xls
Saved as: google\output_v1_26_07\RDO_50_Sheet_9__DO_38_2021_.xlsx
Processing RDO No. 51 - Pasay City.xls
Saved as: google\output_v1_26_07\RDO_51_Sheet_7__DO_43_2023_.xlsx
Processing RDO No. 52 - Paranaque City.xls
Saved as: google\output_v1_26_07\RDO_52_Sheet_10__DO_049_23_.xlsx
Processing RDO No. 53A - Las Pinas City.xls
Saved as: google\output_v1_26_07\RDO_53A_Sheet_9__DO_004_2021_.xlsx
Processing RDO No. 53B - Muntinlupa City.xls
Saved as: google\output_v1_26_07\RDO_53B_Sheet_10__DO_089_2023_.xlsx
Processing RDO No. 54A - Trece Martirez City, East Cavite.xls
Saved as: google\output_v1_26_07\RDO_54A_Sheet_11__DO_20_21_.xlsx
Processing RDO No. 54B - Bacoor City, West Cavite.xls
Saved as: google\output_v1_26_07\RDO_54B_Sheet_8__DO_33_22_.xlsx
Processing RDO No. 55 - San Pablo City, East Laguna.xls
Saved as: google\output_v1_26_07\RDO_55_Sheet_9__DO_018_20.xlsx
Processing RDO No. 56 - Calamba City, Central Laguna.xls
Saved as: google\output_v1_26_07\RDO_56_Sheet_17__DO_059_23_.xlsx
Processing RDO No. 57 - Biñan City, West Laguna.xls
Saved as: google\output_v1_26_07\RDO_57_Sheet_10__DO_055_24.xlsx
Processing RDO No. 58 - Batangas City, West Batangas.xlsx

C:\Users\oyutn\PycharmProjects\bir-zl-scraping\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

Saved as: google\output_v1_26_07\RDO_58_Sheet_7__DO_35_2022_.xlsx
Processing RDO No. 59 - Lipa City, East Batangas.xls
Saved as: google\output_v1_26_07\RDO_59_Sheet_8__34_22_.xlsx
Processing RDO No. 6 - Urdaneta City, East Pangasinan.xls
Saved as: google\output_v1_26_07\RDO_6_Sheet_11__48_22_.xlsx
Processing RDO No. 60 - Lucena City, North Quezon.xls
Saved as: google\output_v1_26_07\RDO_60_Sheet_7__DO_13_2020_.xlsx
Processing RDO No. 61 - Gumaca, South Quezon.xls
Saved as: google\output_v1_26_07\RDO_61_Sheet_9__DO_037_2022_.xlsx
Processing RDO No. 62 - Boac, Marinduque.xls
Saved as: google\output_v1_26_07\RDO_62_Sheet_4__DO_40_22_.xlsx
Processing RDO No. 63 - Calapan City,  Oriental Mindoro.XLS
Saved as: google\output_v1_26_07\RDO_63_Sheet_6__DO_43_22_.xlsx
Processing RDO No. 64 - Talisay, Camarines Norte.xls
Saved as: google\output_v1_26_07\RDO_64_Sheet_7__DO_015_2024_.xlsx
Processing RDO No. 65 - Naga City, Camarines Sur.xls
Saved as: google\output_v1_26_07\RDO_65_Sheet_8__DO_034_2024_.xlsx
Processing RDO No. 66 - Iriga City, Camarines Sur.xls
Saved as: google\output_v1_26_07\RDO_66_Sheet_4__DO_009_2024_.xlsx
Processing RDO No. 67 - Legazpi City, Albay.xls
Saved as: google\output_v1_26_07\RDO_67_Sheet_7__DO_016_2024_.xlsx
Processing RDO No. 68 - Sorsogon City, Sorsogon.xls
Saved as: google\output_v1_26_07\RDO_68_Sheet_4__DO_002_2024_.xlsx
Processing RDO No. 69 - Virac, Catanduanes.xls
Saved as: google\output_v1_26_07\RDO_69_Sheet_4__DO_006_2024_.xlsx
Processing RDO No. 7 - Bangued, Abra.xls
Saved as: google\output_v1_26_07\RDO_7_Sheet_4__DO_016_21_.xlsx
Processing RDO No. 70 - Masbate City, Masbate.xls
Saved as: google\output_v1_26_07\RDO_70_Sheet_4__DO_010_2024_.xlsx
Processing RDO No. 71 - Kalibo, Aklan.xls
Saved as: google\output_v1_26_07\RDO_71_Sheet_6__DO_010_2021_.xlsx
Processing RDO No. 72 - Roxas City, Capiz.xls
Saved as: google\output_v1_26_07\RDO_72_Sheet_6__DO_025_2021_.xlsx
Processing RDO No. 73 - San Jose, Antique.xls
Saved as: google\output_v1_26_07\RDO_73_Sheet_4__DO_14_2021_.xlsx
Processing RDO No. 74 - Iloilo City, Iloilo.xls
Saved as: google\output_v1_26_07\RDO_74_Sheet_9__DO17_2021_.xlsx
Processing RDO No. 75 - Zarraga, Iloilo.xls
Saved as: google\output_v1_26_07\RDO_75_Sheet_4__DO_13_2021_.xlsx
Processing RDO No. 76 - Victorias City, Negros Occidental.xls
Saved as: google\output_v1_26_07\RDO_76_Sheet_4__DO_75_2023_.xlsx
Processing RDO No. 77 - Bacolod City Negros Occidental.xls
Saved as: google\output_v1_26_07\RDO_77_Sheet_7__DO_058_2023_.xlsx
Processing RDO No. 78 - Binalbagan, Negros Occidental.xls
Saved as: google\output_v1_26_07\RDO_78_Sheet_10__077_23_.xlsx
Processing RDO No. 79 - Dumaguete City, Negros Oriental.xls
Saved as: google\output_v1_26_07\RDO_79_Sheet_3__DO_078_2018_.xlsx
Processing RDO No. 8 - Baguio City.xls
Saved as: google\output_v1_26_07\RDO_8_Sheet_5__DO_074_23_.xlsx
Processing RDO No. 80 - Mandaue City, Cebu.xls
Saved as: google\output_v1_26_07\RDO_80__Sheet_11__DO_23_2022_.xlsx
Processing RDO No. 81 - Cebu City North.xlsx
Saved as: google\output_v1_26_07\RDO_81_Sheet_6__DO_054_2023_.xlsx
Processing RDO No. 82 - Cebu City, South.xls
Saved as: google\output_v1_26_07\RDO_82_Sheet_6__DO_86_2023_.xlsx
Processing RDO No. 83 - Talisay City, CebuWeb.xls
Saved as: google\output_v1_26_07\RDO_83_Sheet_8_060_22_.xlsx
Processing RDO No. 84 - Tagbilaran City, Bohol.XLS
Saved as: google\output_v1_26_07\RDO_84_Sheet_6__DO_043_2024_.xlsx
Processing RDO No. 85 - Catarman, Northern Samar.xls
Saved as: google\output_v1_26_07\RDO_85_Sheet_4__DO_053_24_.xlsx
Processing RDO No. 86 - Borongan City, Eastern Samar.xls
Saved as: google\output_v1_26_07\RDO_86_Sheet_4__DO_07_2019_.xlsx
Processing RDO No. 87 - Catbalogan City.xls
Saved as: google\output_v1_26_07\RDO_87_Sheet_3__D0_19_2010_.xlsx
Processing RDO No. 88 - Tacloban City, Leyte.xls
Saved as: google\output_v1_26_07\RDO_88_Sheet_10__DO_011_24_.xlsx
Processing RDO No. 89 - Ormoc City, Leyte.xls
Saved as: google\output_v1_26_07\RDO_89_Sheet_7__DO_042_2024_.xlsx
Processing RDO No. 9 - La Trinidad, Benguet.xlsx
Saved as: google\output_v1_26_07\RDO_9_Sheet_3__DO_12_2018_.xlsx
Processing RDO No. 90 - Maasin City, Southern Leyte.xls
Saved as: google\output_v1_26_07\RDO_90_Sheet_5__DO_NO__055_2023_.xlsx
Processing RDO No. 91 - Dipolog City, Zamboanga del Norte.xls
Saved as: google\output_v1_26_07\RDO_91_Sheet_6__DO_073_2018_.xlsx
Processing RDO No. 92 - Pagadian City, Zamboanga del Sur.xls
Saved as: google\output_v1_26_07\RDO_92_Sheet_4__DO_014_2023_.xlsx
Processing RDO No. 93A - Zamboanga City, Zamboanga Del Sur.xlsx
Saved as: google\output_v1_26_07\RDO_93A_Sheet_5__DO_008_2024_.xlsx
Processing RDO No. 93B - Ipil, Zamboanga Sibugay (WEBSITE REUPLOADING).xls
Saved as: google\output_v1_26_07\RDO_93B_Sheet_4__DO_58_2019_.xlsx
Processing RDO No. 94 - Isabela City,  Basilan.xls
Saved as: google\output_v1_26_07\RDO_94_Sheet_2__DO_031_2023_.xlsx
Processing RDO No. 95 - Jolo, Sulu.xls
Saved as: google\output_v1_26_07\RDO_95_Sheet_2__DO_003_2021_.xlsx
Processing RDO No. 96 - Bongao, Tawi-Tawi.xls
Saved as: google\output_v1_26_07\RDO_96_Sheet_5__DO_45_23_.xlsx
Processing RDO No. 97 - Gingoog City, Misamis Oriental.xls
Saved as: google\output_v1_26_07\RDO_97_Sheet_7__DO_012_2023_.xlsx
Processing RDO No. 98 - Cagayan de Oro City, Misamis Oriental.xls
Saved as: google\output_v1_26_07\RDO_98_Sheet_9__DO_032_2023_.xlsx
Processing RDO No. 99 - Malaybalay City, Bukidnon.xlsx
Saved as: google\output_v1_26_07\RDO_99_Sheet_4__DO_047___22_.xlsx

Writing 1203866 annotations to google\output_v1_26_07\annotations.csv
Annotations saved successfully to google\output_v1_26_07\annotations.csv

Processing complete: 122 files processed, 0 files skipped.
Output directory: google\output_v1_26_07

'google\\output_v1_26_07'

In [2]:
process_excel_files(base_output_dir="refactor", use_alternate="v3")

Creating output directory: refactor\output_v1_26_07
Processing RDO No. 1 - Laoag City, Ilocos Norte.xls
Saved as: refactor\output_v1_26_07\RDO_1_Sheet_9__DO_047_2023_.xlsx
Processing RDO No. 10 - Bontoc, Mt. Province.xls
Saved as: refactor\output_v1_26_07\RDO_10_Sheet_3__DO_044_2022_.xlsx
Processing RDO No. 100 - Ozamiz City, Misamis Occidental.xls
Saved as: refactor\output_v1_26_07\RDO_100_Sheet_5__DO_27_2020_.xlsx
Processing RDO No. 101 - Iligan City, Lanao del Norte.xls
Saved as: refactor\output_v1_26_07\RDO_101_Sheet_6__DO_029_20_.xlsx
Processing RDO No. 102 - Marawi City, Lanao del Sur.xls
Saved as: refactor\output_v1_26_07\RDO_102_Sheet_2__DO_37_20_.xlsx
Processing RDO No. 103 - Butuan City, Agusan del Norte.xls
Saved as: refactor\output_v1_26_07\RDO_103_Sheet_9__064_2022_.xlsx
Processing RDO No. 104 - Bayugan City, Agusan del Sur.xls
Saved as: refactor\output_v1_26_07\RDO_104_Sheet_5__DO_081_2022_.xlsx
Processing RDO No. 105 - Surigao City, Surigao del Norte.xls
Saved as: refactor\output_v1_26_07\RDO_105_Sheet_5__DO_034_2023_.xlsx
Processing RDO No. 106 - Tandag City, Surigao del Sur.xls
Saved as: refactor\output_v1_26_07\RDO_106_Sheet_5__DO_049_2022_.xlsx
Processing RDO No. 107 - Cotabato City, Maguindanao.xls
Saved as: refactor\output_v1_26_07\RDO_107_Sheet_4__DO_053_2022_.xlsx
Processing RDO No. 108 - Kidapawan City, North Cotabato.xls
Saved as: refactor\output_v1_26_07\RDO_108_Sheet_4__DO_009_2023_.xlsx
Processing RDO No. 109 - Tacurong City, Sultan Kudarat.xls
Saved as: refactor\output_v1_26_07\RDO_109_Sheet_4__DO_07_2023_.xlsx
Processing RDO No. 11 -  Tabuk City, Kalinga.xls
Saved as: refactor\output_v1_26_07\RDO_11_Sheet_4__DO_40_2020_.xlsx
Processing RDO No. 110 - General Santos City, South Cotabato.xls
Saved as: refactor\output_v1_26_07\RDO_110_Sheet_9__DO_027_23.xlsx
Processing RDO No. 111 - Koronadal City, South Cotabato.xls
Saved as: refactor\output_v1_26_07\RDO_111_Sheet_5__DO_075_2022_.xlsx
Processing RDO No. 112 - Tagum City, Davao del Norte.xlsx
Saved as: refactor\output_v1_26_07\RDO_112_Sheet_5__DO_79_2019_.xlsx
Processing RDO NO. 113A - West Davao City.xlsx
Saved as: refactor\output_v1_26_07\RDO_113A_Sheet_5__DO_032_21_.xlsx
Processing RDO No. 113B - East Davao City.xls
Saved as: refactor\output_v1_26_07\RDO_113B_Sheet_5__033_2021_.xlsx
Processing RDO No. 114 - Mati City, Davao Oriental.xls
Saved as: refactor\output_v1_26_07\RDO_114_Sheet_4__DO_029_2023_.xlsx
Processing RDO No. 115 - Digos City, Davao del Sur.XLS
Saved as: refactor\output_v1_26_07\RDO_115_Sheet_4__DO_34_2021.xlsx
Processing RDO No. 12 - Lagawe, Ifugao.xlsx
Saved as: refactor\output_v1_26_07\RDO_12_Sheet4__DO_74_18.xlsx
Processing RDO No. 13 - Tuguegarao City, Cagayan.xls
Saved as: refactor\output_v1_26_07\RDO_13_Sheet_8__DO_028_2024_.xlsx
Processing RDO No. 14 - Bayombong, Nueva Vizcaya.xls
Saved as: refactor\output_v1_26_07\RDO_14_Sheet_4__029_22_.xlsx
Processing RDO No. 15 - Naguilian, Isabela.xls
Saved as: refactor\output_v1_26_07\RDO_15_Sheet_3__DO_23_2023_.xlsx
Processing RDO No. 16 - Cabarroguis, Quirino.xls
Saved as: refactor\output_v1_26_07\RDO_16_Sheet_4__DO_30_22_.xlsx
Processing RDO No. 17A - Tarlac City, Tarlac.xls
Saved as: refactor\output_v1_26_07\RDO_17A_Sheet_4__DO_15_2020_.xlsx
Processing RDO No. 17B - Paniqui Tarlac.xls
Saved as: refactor\output_v1_26_07\RDO_17B_Sheet_4__DO_40_21_.xlsx
Processing RDO No. 18 - Olongapo City, Zambales.xls
Saved as: refactor\output_v1_26_07\RDO_18_Sheet_4__DO_19_22_.xlsx
Processing RDO No. 2 - Vigan City, Ilocos Sur.xls
Saved as: refactor\output_v1_26_07\RDO_2_Sheet_5__DO_28_23_.xlsx
Processing RDO No. 20 - Balanga City, Bataan.xls
Saved as: refactor\output_v1_26_07\RDO_20_Sheet_4__DO_22_2022_.xlsx
Processing RDO No. 21A - Angeles City, North Pampanga.xls
Saved as: refactor\output_v1_26_07\RDO_21A_Sheet_6__DO_056_22_.xlsx
Processing RDO No. 21B - City of San Fernando, South Pampanga.xls
Saved as: refactor\output_v1_26_07\RDO_21B_Sheet_9__DO_004_2024_.xlsx
Processing RDO No. 22 - Baler Aurora.xls
Saved as: refactor\output_v1_26_07\RDO_22_Sheet_4__DO_69_2023_.xlsx
Processing RDO No. 23A - Talavera, North Nueva Ecija.xls
Saved as: refactor\output_v1_26_07\RDO_23A_Sheet_4__DO_50_2023_.xlsx
Processing RDO No. 23B - Cabanatuan City, South Nueva Ecija.xls
Saved as: refactor\output_v1_26_07\RDO_23B_Sheet_5__DO_39_22_.xlsx
Processing RDO No. 24 - Valenzuela City.xls
Saved as: refactor\output_v1_26_07\RDO_24_Sheet_6__DO_009_2021_.xlsx
Processing RDO No. 25A - Plaridel, Bulacan.xlsx
Saved as: refactor\output_v1_26_07\RDO_25A_Sheet_9__DO_009_2020_.xlsx
Processing RDO No. 25B - Sta. Maria, Bulacan.xlsx
Saved as: refactor\output_v1_26_07\RDO_25B_Sheet_9__DO_14_18_.xlsx
Processing RDO No. 26 - Malabon-Navotas.xls
Saved as: refactor\output_v1_26_07\RDO_26_Sheet_8__DO_046_2022_.xlsx
Processing RDO No. 27 - Caloocan City.xls
Saved as: refactor\output_v1_26_07\RDO_27_Sheet_8__DO_046_2023_.xlsx
Processing RDO No. 28 - Novaliches, Quezon City.xls
Saved as: refactor\output_v1_26_07\RDO_28_Sheet_8__DO_037_2024_.xlsx
Processing RDO No. 29 - Tondo-San Nicolas.xls
Saved as: refactor\output_v1_26_07\RDO_29_Sheet_7__DO_27_19_.xlsx
Processing RDO No. 3 - San Fernando City, La Union.xls
Saved as: refactor\output_v1_26_07\RDO_3_Sheet_8__DO_045_19__.xlsx
Processing RDO No. 30 - Binondo.xls
Saved as: refactor\output_v1_26_07\RDO_30_Sheet_6__DO_62_17_.xlsx
Processing RDO No. 31 - Sta. Cruz, Manila.xls
Saved as: refactor\output_v1_26_07\RDO_31_Sheet_6__DO_077_18_.xlsx
Processing RDO No. 32 - Quiapo-Sampaloc-San Miguel-Sta Mesa.xls
Saved as: refactor\output_v1_26_07\RDO_32_Sheet_6__DO_21_19_.xlsx
Processing RDO No. 33 - Intramuros-Ermita-Malate.xls
Saved as: refactor\output_v1_26_07\RDO_33_Sheet_6__DO_75_17_.xlsx
Processing RDO No. 34 - Paco-Pandacan-Sta. Ana-San Andres.xls
Saved as: refactor\output_v1_26_07\RDO_34_Sheet_6__DO_78_19_.xlsx
Processing RDO No. 35 - Odiongan, Romblon.xls
Saved as: refactor\output_v1_26_07\RDO_35_Sheet_3__DO_026_2021_.xlsx
Processing RDO No. 36 - Puerto Princesa City, Palawan.xls
Saved as: refactor\output_v1_26_07\RDO_36_Sheet_3__DO_72_17.xlsx
Processing RDO No. 37 - SanJose, Occidental Mindoro.xls
Saved as: refactor\output_v1_26_07\RDO_37_Sheet_4__DO_045_2022_.xlsx
Processing RDO No. 38 - North Quezon City.xls
Saved as: refactor\output_v1_26_07\RDO_38_Sheet_8__DO_033_2024_.xlsx
Processing RDO No. 39 - South Quezon City.xls
Saved as: refactor\output_v1_26_07\RDO_39_Sheet_8__DO_007_2024_.xlsx
Processing RDO No. 4 - Calasiao, Central Pangasinan.xls
Saved as: refactor\output_v1_26_07\RDO_4_Sheet_12__DO015_2023_.xlsx
Processing RDO No. 40 - Cubao.xls
Saved as: refactor\output_v1_26_07\RDO_40_Sheet_8__DO_035_2024_.xlsx
Processing RDO No. 41 - Mandaluyong City.xls
Saved as: refactor\output_v1_26_07\RDO_41_Sheet_9__DO_059_2022.xlsx
Processing RDO No. 42 - San Juan City.xls
Saved as: refactor\output_v1_26_07\RDO_42_Sheet_8__DO_022_2023_.xlsx
Processing RDO No. 43 - Pasig City.xls
Saved as: refactor\output_v1_26_07\RDO_43_Sheet_9__DO_24_2023_.xlsx
Processing RDO No. 44 - Taguig-Pateros.xlsx
Saved as: refactor\output_v1_26_07\RDO_44_Sheet_9__DO_005_24_.xlsx
Processing RDO No. 45 - Marikina City.xls
Saved as: refactor\output_v1_26_07\RDO_45_Sheet_11__DO_06_2023_.xlsx
Processing RDO No. 46 - Cainta-Taytay.xls
Saved as: refactor\output_v1_26_07\RDO_46_Sheet_7__DO_22_2020_.xlsx
Processing RDO No. 47 - East Makati.xls
Saved as: refactor\output_v1_26_07\RDO_47_Sheet_8__DO_37_2021_.xlsx
Processing RDO No. 48 - West Makati.xls
Saved as: refactor\output_v1_26_07\RDO_48_Sheet_9__DO_36_2021_.xlsx
Processing RDO No. 49 - North Makati City.xls
Saved as: refactor\output_v1_26_07\RDO_49_Sheet_7__DO_35_2021_.xlsx
Processing RDO No. 5 - Alaminos City, West Pangasinan.xls
Saved as: refactor\output_v1_26_07\RDO_5_Sheet_11__DO_082_2022_.xlsx
Processing RDO No. 50 - South Makati.xls
Saved as: refactor\output_v1_26_07\RDO_50_Sheet_9__DO_38_2021_.xlsx
Processing RDO No. 51 - Pasay City.xls
Saved as: refactor\output_v1_26_07\RDO_51_Sheet_7__DO_43_2023_.xlsx
Processing RDO No. 52 - Paranaque City.xls
Saved as: refactor\output_v1_26_07\RDO_52_Sheet_10__DO_049_23_.xlsx
Processing RDO No. 53A - Las Pinas City.xls
Saved as: refactor\output_v1_26_07\RDO_53A_Sheet_9__DO_004_2021_.xlsx
Processing RDO No. 53B - Muntinlupa City.xls
Saved as: refactor\output_v1_26_07\RDO_53B_Sheet_10__DO_089_2023_.xlsx
Processing RDO No. 54A - Trece Martirez City, East Cavite.xls
Saved as: refactor\output_v1_26_07\RDO_54A_Sheet_11__DO_20_21_.xlsx
Processing RDO No. 54B - Bacoor City, West Cavite.xls
Saved as: refactor\output_v1_26_07\RDO_54B_Sheet_8__DO_33_22_.xlsx
Processing RDO No. 55 - San Pablo City, East Laguna.xls
Saved as: refactor\output_v1_26_07\RDO_55_Sheet_9__DO_018_20.xlsx
Processing RDO No. 56 - Calamba City, Central Laguna.xls
Saved as: refactor\output_v1_26_07\RDO_56_Sheet_17__DO_059_23_.xlsx
Processing RDO No. 57 - Biñan City, West Laguna.xls
Saved as: refactor\output_v1_26_07\RDO_57_Sheet_10__DO_055_24.xlsx
Processing RDO No. 58 - Batangas City, West Batangas.xlsx

C:\Users\oyutn\PycharmProjects\bir-zl-scraping\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

Saved as: refactor\output_v1_26_07\RDO_58_Sheet_7__DO_35_2022_.xlsx
Processing RDO No. 59 - Lipa City, East Batangas.xls
Saved as: refactor\output_v1_26_07\RDO_59_Sheet_8__34_22_.xlsx
Processing RDO No. 6 - Urdaneta City, East Pangasinan.xls
Saved as: refactor\output_v1_26_07\RDO_6_Sheet_11__48_22_.xlsx
Processing RDO No. 60 - Lucena City, North Quezon.xls
Saved as: refactor\output_v1_26_07\RDO_60_Sheet_7__DO_13_2020_.xlsx
Processing RDO No. 61 - Gumaca, South Quezon.xls
Saved as: refactor\output_v1_26_07\RDO_61_Sheet_9__DO_037_2022_.xlsx
Processing RDO No. 62 - Boac, Marinduque.xls
Saved as: refactor\output_v1_26_07\RDO_62_Sheet_4__DO_40_22_.xlsx
Processing RDO No. 63 - Calapan City,  Oriental Mindoro.XLS
Saved as: refactor\output_v1_26_07\RDO_63_Sheet_6__DO_43_22_.xlsx
Processing RDO No. 64 - Talisay, Camarines Norte.xls
Saved as: refactor\output_v1_26_07\RDO_64_Sheet_7__DO_015_2024_.xlsx
Processing RDO No. 65 - Naga City, Camarines Sur.xls
Saved as: refactor\output_v1_26_07\RDO_65_Sheet_8__DO_034_2024_.xlsx
Processing RDO No. 66 - Iriga City, Camarines Sur.xls
Saved as: refactor\output_v1_26_07\RDO_66_Sheet_4__DO_009_2024_.xlsx
Processing RDO No. 67 - Legazpi City, Albay.xls
Saved as: refactor\output_v1_26_07\RDO_67_Sheet_7__DO_016_2024_.xlsx
Processing RDO No. 68 - Sorsogon City, Sorsogon.xls
Saved as: refactor\output_v1_26_07\RDO_68_Sheet_4__DO_002_2024_.xlsx
Processing RDO No. 69 - Virac, Catanduanes.xls
Saved as: refactor\output_v1_26_07\RDO_69_Sheet_4__DO_006_2024_.xlsx
Processing RDO No. 7 - Bangued, Abra.xls
Saved as: refactor\output_v1_26_07\RDO_7_Sheet_4__DO_016_21_.xlsx
Processing RDO No. 70 - Masbate City, Masbate.xls
Saved as: refactor\output_v1_26_07\RDO_70_Sheet_4__DO_010_2024_.xlsx
Processing RDO No. 71 - Kalibo, Aklan.xls
Saved as: refactor\output_v1_26_07\RDO_71_Sheet_6__DO_010_2021_.xlsx
Processing RDO No. 72 - Roxas City, Capiz.xls
Saved as: refactor\output_v1_26_07\RDO_72_Sheet_6__DO_025_2021_.xlsx
Processing RDO No. 73 - San Jose, Antique.xls
Saved as: refactor\output_v1_26_07\RDO_73_Sheet_4__DO_14_2021_.xlsx
Processing RDO No. 74 - Iloilo City, Iloilo.xls
Saved as: refactor\output_v1_26_07\RDO_74_Sheet_9__DO17_2021_.xlsx
Processing RDO No. 75 - Zarraga, Iloilo.xls
Saved as: refactor\output_v1_26_07\RDO_75_Sheet_4__DO_13_2021_.xlsx
Processing RDO No. 76 - Victorias City, Negros Occidental.xls
Saved as: refactor\output_v1_26_07\RDO_76_Sheet_4__DO_75_2023_.xlsx
Processing RDO No. 77 - Bacolod City Negros Occidental.xls
Saved as: refactor\output_v1_26_07\RDO_77_Sheet_7__DO_058_2023_.xlsx
Processing RDO No. 78 - Binalbagan, Negros Occidental.xls
Saved as: refactor\output_v1_26_07\RDO_78_Sheet_10__077_23_.xlsx
Processing RDO No. 79 - Dumaguete City, Negros Oriental.xls
Saved as: refactor\output_v1_26_07\RDO_79_Sheet_3__DO_078_2018_.xlsx
Processing RDO No. 8 - Baguio City.xls
Saved as: refactor\output_v1_26_07\RDO_8_Sheet_5__DO_074_23_.xlsx
Processing RDO No. 80 - Mandaue City, Cebu.xls
Saved as: refactor\output_v1_26_07\RDO_80__Sheet_11__DO_23_2022_.xlsx
Processing RDO No. 81 - Cebu City North.xlsx
Saved as: refactor\output_v1_26_07\RDO_81_Sheet_6__DO_054_2023_.xlsx
Processing RDO No. 82 - Cebu City, South.xls
Saved as: refactor\output_v1_26_07\RDO_82_Sheet_6__DO_86_2023_.xlsx
Processing RDO No. 83 - Talisay City, CebuWeb.xls
Saved as: refactor\output_v1_26_07\RDO_83_Sheet_8_060_22_.xlsx
Processing RDO No. 84 - Tagbilaran City, Bohol.XLS
Saved as: refactor\output_v1_26_07\RDO_84_Sheet_6__DO_043_2024_.xlsx
Processing RDO No. 85 - Catarman, Northern Samar.xls
Saved as: refactor\output_v1_26_07\RDO_85_Sheet_4__DO_053_24_.xlsx
Processing RDO No. 86 - Borongan City, Eastern Samar.xls
Saved as: refactor\output_v1_26_07\RDO_86_Sheet_4__DO_07_2019_.xlsx
Processing RDO No. 87 - Catbalogan City.xls
Saved as: refactor\output_v1_26_07\RDO_87_Sheet_3__D0_19_2010_.xlsx
Processing RDO No. 88 - Tacloban City, Leyte.xls
Saved as: refactor\output_v1_26_07\RDO_88_Sheet_10__DO_011_24_.xlsx
Processing RDO No. 89 - Ormoc City, Leyte.xls
Saved as: refactor\output_v1_26_07\RDO_89_Sheet_7__DO_042_2024_.xlsx
Processing RDO No. 9 - La Trinidad, Benguet.xlsx
Saved as: refactor\output_v1_26_07\RDO_9_Sheet_3__DO_12_2018_.xlsx
Processing RDO No. 90 - Maasin City, Southern Leyte.xls
Saved as: refactor\output_v1_26_07\RDO_90_Sheet_5__DO_NO__055_2023_.xlsx
Processing RDO No. 91 - Dipolog City, Zamboanga del Norte.xls
Saved as: refactor\output_v1_26_07\RDO_91_Sheet_6__DO_073_2018_.xlsx
Processing RDO No. 92 - Pagadian City, Zamboanga del Sur.xls
Saved as: refactor\output_v1_26_07\RDO_92_Sheet_4__DO_014_2023_.xlsx
Processing RDO No. 93A - Zamboanga City, Zamboanga Del Sur.xlsx
Saved as: refactor\output_v1_26_07\RDO_93A_Sheet_5__DO_008_2024_.xlsx
Processing RDO No. 93B - Ipil, Zamboanga Sibugay (WEBSITE REUPLOADING).xls
Saved as: refactor\output_v1_26_07\RDO_93B_Sheet_4__DO_58_2019_.xlsx
Processing RDO No. 94 - Isabela City,  Basilan.xls
Saved as: refactor\output_v1_26_07\RDO_94_Sheet_2__DO_031_2023_.xlsx
Processing RDO No. 95 - Jolo, Sulu.xls
Saved as: refactor\output_v1_26_07\RDO_95_Sheet_2__DO_003_2021_.xlsx
Processing RDO No. 96 - Bongao, Tawi-Tawi.xls
Saved as: refactor\output_v1_26_07\RDO_96_Sheet_5__DO_45_23_.xlsx
Processing RDO No. 97 - Gingoog City, Misamis Oriental.xls
Saved as: refactor\output_v1_26_07\RDO_97_Sheet_7__DO_012_2023_.xlsx
Processing RDO No. 98 - Cagayan de Oro City, Misamis Oriental.xls
Saved as: refactor\output_v1_26_07\RDO_98_Sheet_9__DO_032_2023_.xlsx
Processing RDO No. 99 - Malaybalay City, Bukidnon.xlsx
Saved as: refactor\output_v1_26_07\RDO_99_Sheet_4__DO_047___22_.xlsx

Writing 1203866 annotations to refactor\output_v1_26_07\annotations.csv
Annotations saved successfully to refactor\output_v1_26_07\annotations.csv

Processing complete: 122 files processed, 0 files skipped.
Output directory: refactor\output_v1_26_07

'refactor\\output_v1_26_07'

In [4]:
import pandas as pd

from test_functions import *
from functions import *
from file_manager import *


from utils import *
from compare_directories import *

In [5]:
comparator = DirectoryDataFrameComparator("google/output_v1_26_07", "refactor/output_v1_26_07", output_dir="./")

In [6]:
one = comparator.run(unique_only=False)

Comparing files:  63%|██████▎   | 77/123 [01:49<01:01,  1.34s/pair]

Error comparing files google\output_v1_26_07\annotations.csv and refactor\output_v1_26_07\annotations.csv: Excel file format cannot be determined, you must specify an engine manually.

Comparing files: 100%|██████████| 123/123 [03:08<00:00,  1.53s/pair]

Comparisons complete!

In [9]:
one

Empty DataFrame
Columns: [idx, df1_value, df2_value, column, remarks, df1_filename, df2_filename]
Index: []

In [13]:
one['remarks'].value_counts()

remarks
Missing value    306
Name: count, dtype: int64

In [14]:
comparator2 = DirectoryDataFrameComparator("mine/output_v3_26_07", "google/output_v1_26_07", output_dir="./")

In [15]:
two = comparator2.run(unique_only=False)

Comparing files: 100%|██████████| 121/121 [03:05<00:00,  1.54s/pair]

Comparisons complete!

In [16]:
two

,idx,df1_value,df2_value,column,remarks,df1_filename,df2_filename
0,4649,WITHOUT ROAD ACCESS*,,Vicinity,Missing value,RDO_105_Sheet_5__DO_034_2023_.xlsx,RDO_105_Sheet_5__DO_034_2023_.xlsx
1,4650,WITHOUT ROAD ACCESS*,,Vicinity,Missing value,RDO_105_Sheet_5__DO_034_2023_.xlsx,RDO_105_Sheet_5__DO_034_2023_.xlsx
2,4651,WITHOUT ROAD ACCESS*,,Vicinity,Missing value,RDO_105_Sheet_5__DO_034_2023_.xlsx,RDO_105_Sheet_5__DO_034_2023_.xlsx
3,4652,WITHOUT ROAD ACCESS*,,Vicinity,Missing value,RDO_105_Sheet_5__DO_034_2023_.xlsx,RDO_105_Sheet_5__DO_034_2023_.xlsx
4,4653,WITHOUT ROAD ACCESS*,,Vicinity,Missing value,RDO_105_Sheet_5__DO_034_2023_.xlsx,RDO_105_Sheet_5__DO_034_2023_.xlsx
...,...,...,...,...,...,...,...
274,17604,INTERIOR,,Vicinity,Missing value,RDO_10_Sheet_3__DO_044_2022_.xlsx,RDO_10_Sheet_3__DO_044_2022_.xlsx
275,17605,INTERIOR,,Vicinity,Missing value,RDO_10_Sheet_3__DO_044_2022_.xlsx,RDO_10_Sheet_3__DO_044_2022_.xlsx
276,17606,INTERIOR,,Vicinity,Missing value,RDO_10_Sheet_3__DO_044_2022_.xlsx,RDO_10_Sheet_3__DO_044_2022_.xlsx
277,17607,INTERIOR,,Vicinity,Missing value,RDO_10_Sheet_3__DO_044_2022_.xlsx,RDO_10_Sheet_3__DO_044_2022_.xlsx
278,17608,INTERIOR,,Vicinity,Missing value,RDO_10_Sheet_3__DO_044_2022_.xlsx,RDO_10_Sheet_3__DO_044_2022_.xlsx

In [15]:
from processing.file_manager import MusicFileManager

In [17]:
data_files = MusicFileManager(base_path="../data")

VBox(children=(Dropdown(description='Select piece:', layout=Layout(width='500px'), options=(('RDO No. 1 - Laoa…

In [19]:
file_info = data_files.selected_file_info
filename = file_info["filename"]
df_raw, sheet_name_used = xls_to_df(file_info["filename"], base_dir="../data/")

In [20]:
df_raw.to_numpy()

array([['Republic of the Philippines', nan, nan, nan],
       ['DEPARTMENT OF FINANCE', nan, nan, nan],
       ['Manila', nan, nan, nan],
       ...,
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       ['I-3/apmd (fet 03-06-2020)', nan, nan, nan]],
      shape=(7685, 4), dtype=object)

In [ ]:
_ = annotate(df_raw, file_name=filename, sheet_name=sheet_name_used, debug=False)

In [ ]:
collected_annotations

In [ ]:
final = json.dumps(collected_annotations)

In [ ]:
with open("data.json", "w") as f:
    json.dump(collected_annotations, f, indent=4)  # `indent` makes it more readable